spring.application.name=compras-service
server.port=${SERVER_PORT:8084}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/compras_db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:compras_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:compras_pass}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

auth.service.url=${AUTH_SERVICE_URL:http://localhost:8083/api/auth}

